name: AdvancedPotion
version: '${project.version}'
main: yusama125718.advancedpotion.AdvancedPotion
api-version: 1.17
authors: [ yusama125718 ]

commands:
  advpot:
    description: Advanced Potion
    usage: /advpot helpでコマンドを確認

permissions:
  advpot.op:
    default: op